### ISSUE TITLE
Who coded this?

### ISSUE THREAD

**Issue by ryancorridor** [aggie-coding-club/workshops-spring-2020#4]
This need to be changed to a plus sign.

https://github.com/aggie-coding-club/workshops-spring-2020/blob/2c2cba044f65dfd20fe8e2e9daf9da77999c0d07/PM-Training/main.py#L2

**Comment by shreyshah33** [comment]
https://github.com/aggie-coding-club/workshops-spring-2020/commit/736e2edb1deac35f07374365754cfaf759cb0b78

This fixes the issue.
